### ISSUE TITLE
飞书版本 or 飞书路径

### ISSUE THREAD

**Issue by qiuyueovo** [starccy/feishu-unreadme#1]
现在一直报错：
未找到 messenger.asar，可能是飞书安装目录指定的不正确，或版本不兼容。
当前飞书版本：7.15.9
安装目录：D:\Program Files\Feishu

**Comment by qiuyueovo** [comment]
感觉这个思路很好，现在飞书方面似乎没有类似这种 “永不已读” 的功能

**Comment by starccy** [comment]
请确认下是否有这个文件呢？ `D:\Program Files\Feishu\app\webcontent\messenger.asar`.   
如果有的话大概是路径包含了空格的问题，请使用 `"` 双引号将路径括起来。

**Comment by qiuyueovo** [comment]
> 请确认下是否有这个文件呢？ `D:\Program Files\Feishu\app\webcontent\messenger.asar`. 如果有的话大概是路径包含了空格的问题，请使用 `"` 双引号将路径括起来。

有这个文件的，特意去看了一下。我试一下吧 双引号

**Comment by qiuyueovo** [comment]
![image](https://github.com/starccy/feishu-unreadme/assets/40270698/04e93d40-9028-481a-993c-d753d5624bb4)
目前会有这个报错，查看了下确实有这个文件。但是不知道是什么时候有的。

**Comment by qiuyueovo** [comment]
> ![image](https://private-user-images.githubusercontent.com/40270698/325138446-04e93d40-9028-481a-993c-d753d5624bb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDcxMDYsIm5iZiI6MTcxMzk0NjgwNiwicGF0aCI6Ii80MDI3MDY5OC8zMjUxMzg0NDYtMDRlOTNkNDAtOTAyOC00ODFhLTk5M2MtZDc1M2Q1NjI0YmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YTIwYmFkMmFiMWNiYjRmNDk0MWY0NTg1YTMwZjQ3NWMyZTljMTNkNDMyNmYzMmNiNGY2MjFiMjJiZjdmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aNGt1s57-b8Si8mVI__nQP58rFm9gZVzUxuVhadLNzs) 目前会有这个报错，查看了下确实有这个文件。但是不知道是什么时候有的。

之前这边安装过一次飞书的防撤回工具。可能是更改了这个文件？

**Comment by starccy** [comment]
先把飞书进程都关掉，删除 `app\webcontent\messenger.asar.bak` 再执行脚本呢？   
看样子是由于上一次执行时候文件占用导致文件移动失败。

**Comment by qiuyueovo** [comment]
> 先把飞书进程都关掉，删除 `app\webcontent\messenger.asar.bak` 再执行脚本呢？ 看样子是由于上一次执行时候文件占用导致文件移动失败。

我尝试验证一下，现在是可以正常打开使用的。

**Comment by qiuyueovo** [comment]
> > 先把飞书进程都关掉，删除 `app\webcontent\messenger.asar.bak` 再执行脚本呢？ 看样子是由于上一次执行时候文件占用导致文件移动失败。
> 
> 我尝试验证一下，现在是可以正常打开使用的。

验证了一下 是可以的。
我吧这个 github 的地址分享给别人一下。有一个防撤回的功能，我觉得可以和这些结合起来。

**Comment by starccy** [comment]
目前这个脚本还挺简陋的，不知道防撤回那边是如何是实现的，有时间学习一下。🙏

**Comment by qiuyueovo** [comment]
> 目前这个脚本还挺简陋的，不知道防撤回那边是如何是实现的，有时间学习一下。🙏

https://github.com/flydoos/FeiShuRevokeMsgPatcher
这个是防撤回的，但是没有开源。大概技术是 用了逆向相关的。然后本地更改了一些文件之类的。他这个是闭源的。版本不同的话，补丁也不同。感觉和市面上 微信 防撤回的逻辑差不多。只是微信的更加成熟一些。
