### ISSUE TITLE
消息回复后不显示已读 && 新的想法

### ISSUE THREAD

**Issue by qiuyueovo** [starccy/feishu-unreadme#2]
bug： 在回复消息之后，消息仍然未显示已读，这样会有点假。

新的功能需求：有一些非开发者是没有安装相关python环境的，这样有一些不友好。

另外感谢这个 永不已读的思路🙏

昨天我和另外一位防撤回的开发者聊了一下。他昨天晚上已经肝出来了。可以看一下。但是我不知道具体的实现方式。
https://github.com/flydoos/FeiShuRevokeMsgPatcher

**Comment by qiuyueovo** [comment]
> bug： 在回复消息之后，消息仍然未显示已读，这样会有点假。
> 
> 新的功能需求：有一些非开发者是没有安装相关python环境的，这样有一些不友好。
> 
> 另外感谢这个 永不已读的思路🙏
> 
> 昨天我和另外一位防撤回的开发者聊了一下。他昨天晚上已经肝出来了。可以看一下。但是我不知道具体的实现方式。 https://github.com/flydoos/FeiShuRevokeMsgPatcher

回复消息后，会自动把最近的几条消息标记已读，避免露馅

**Comment by starccy** [comment]
可以考虑。那个项目的功能看起来更完美，可惜不开源我也不用 Windows.

**Comment by qiuyueovo** [comment]
> 可以考虑。那个项目的功能看起来更完美，可惜不开源我也不用 Windows.

确实，这些都是用了逆向的。一般都闭源的，而且也不会公开，版本更新后补丁也需要同步更新。
